### ISSUE TITLE
can't connect to a digital ocean managed Redis cluster on version 5.0.6

### ISSUE THREAD

**Issue by jupitern** [clue/reactphp-redis#100]
Hi,
I can't connect to a digital ocean managed Redis cluster on version 5.0.6
With the code bellow I get the error "Unable to subscribe: Connection to Redis server failed because AUTH command failed"
But using only predis I can cannot with no issues. Can you help me? I think the issue is with the fact that it uses tls

````
       $connector = new \React\Socket\Connector($loop, array(
            'tls' => array(
                'verify_peer' => false,
                'verify_peer_name' => false
            )
        ));

        $factory = new Factory($loop, $connector);

        $client = $factory->createLazyClient(
            'redis://'.$settings['host'].':'.$settings['port'].'?password='.$settings['password'].'&db='.$settings['database']
        );
````

Error: Unable to subscribe: Connection to Redis server failed because AUTH command failed

**Comment by jupitern** [comment]
rediss://

**Comment by clue** [comment]
@jupitern Thanks for reporting back and happy to hear you've got this sorted out by using an encrypted connection using the `rediss://` URL scheme.
