### ISSUE TITLE
PubSub commands limited to single argument (EINVAL)

### ISSUE THREAD

**Issue by szado** [clue/reactphp-redis#121]
I noticed that this library limits number of channels to subscribe/unsubscribe in single query, although the redis docs says it is possible: https://redis.io/commands/subscribe/.
What's the reason for this performance-affecting behavior? Will it be allowed in future releases?

Edit: I found partial answer in readme:

> Each of the above methods follows normal request-response semantics and return a [Promise](https://github.com/clue/reactphp-redis#promises) to await successful subscriptions. Note that while Redis allows a variable number of arguments for each of these commands, this library is currently limited to single arguments for each of these methods in order to match exactly one response to each command request. As an alternative, the methods can simply be invoked multiple times with one argument each.

**Comment by clue** [comment]
> The `SUBSCRIBE`-family of commands do not follow request-response semantics anymore if not called with exactly one parameter. It was thus limited to only accept a single argument per invocation as originally implemented in #24.
>
> As an alternative, you can simply call `SUBSCRIBE`-family of commands any number of times with one argument each.
>
> – Answered in issue #75 

```php
// instead of
$redis->subscribe('foo', 'bar', 'baz');

// call this instead
$redis->subscribe('foo');
$redis->subscribe('bar');
$redis->subscribe('baz');
```

I hope this helps! :+1: If so, consider supporting this project, for example by [becoming a sponsor](https://github.com/sponsors/clue) ❤️
