### ISSUE TITLE
Incorrect code in the documentation

### ISSUE THREAD

**Issue by fx1234** [clue/reactphp-redis#124]
Hi

first of all: great project! thanks for that

It is about the following code (under _Promises_ in the documentation):

```
$redis->get($key)->then(function (string $value) {
    var_dump($value);
}, function (Exception $e) {
    echo 'Error: ' . $e->getMessage() . PHP_EOL;
});
```

the problem is if the _key_ doesn't exist, the returned value is NULL. therefore nothing will happen because a string-value is expected in the function.

**Comment by SimonFrings** [comment]
Hey @fx1234 thanks for pointing this out :+1:

This is a mistake inside the documentation, it should read:
```
$redis->get($key)->then(function (?string $value) {
...
```
If you want you can fill in a PR that fixes this (May also be the case in other chapters of the documentation).
