### ISSUE TITLE
Stream Redis responses

### ISSUE THREAD

**Issue by fritz-gerneth** [clue/reactphp-redis#137]
At the moment server responses are collected in memory and returned once the respective command has finished. This is rather convenient and a good behavior. In some cases though it is interesting to have access to the response as a stream, and not have it buffered in memory first. 

The scenario we currently have for this is caching & serving HTTP responses. Our response body is large-ish and completely stored in Redis. Application logic is to get the data from Redis, and return it as part of the Response. This posses two problems for us: we need to wait for the entire response to be sent to the application, and keep the entire response in memory. Streaming the response would eliminating both aspects, we could pass the Redis response stream to the HTTP response body. 
I did not yet have a detailed look into Redis streams, but might be interesting for these too. 

A second scenario we were experiencing these days is the ability to pass streams to Redis. In our instance the response of an upstream service we were receiving as a stream. We wanted that response to save to Redis (`set`). 

This certainly is not trivial to implement, or rather more to design though. Some level of protocol parsing still needs to be going on, and only the actual payload should be added to the result stream. Any non-scalar response is hard to stream too and, How would this work with command pipelining?

**Comment by SimonFrings** [comment]
Hey @fritz-gerneth, sounds like an interesting use case.

Instead of getting all the data at once from Redis you could also work with smaller chunks by using substrings in combination with https://redis.io/commands/append/.

> This certainly is not trivial to implement, or rather more to design though.

I agree, maybe my suggestion above could be an answer here, what do you think?

**Comment by fritz-gerneth** [comment]
> Instead of getting all the data at once from Redis you could also work with smaller chunks by using substrings in combination with https://redis.io/commands/append/. 

I can see this working. For writing this probably could work reasonably well, especially if we receive a chunked data. Though I think for reading the overhead would pretty harsh (with redis not running on localhost). It would be a trade-off between memory usage and time needed to fetch the data (roundtrips to redis). 

For now we decided to go with higher memory usage and slightly longer time to first byte sent. For larger payloads we probably would go with chunking though (or not store them in redis in the first place).

**Comment by SimonFrings** [comment]
> For now we decided to go with higher memory usage and slightly longer time to first byte sent. For larger payloads we probably would go with chunking though (or not store them in redis in the first place).

Seems like a good answer, I will close this ticket for now, we can reopen this any time if something comes up :+1:
