### ISSUE TITLE
A release with promise v3 unlocked

### ISSUE THREAD

**Issue by WyriHaximus** [clue/reactphp-redis#148]
Got a request for one of my packages to include promise v3 support over at https://github.com/WyriHaximus/reactphp-cache-redis/issues/59. It seems this package's next version branch has support for it through https://github.com/clue/reactphp-redis/pull/145 and https://github.com/clue/reactphp-redis/pull/134. What are the plans for releasing that?

**Comment by SimonFrings** [comment]
Good question @WyriHaximus!

The current version that we're working on is the `v3` as this is also the only milestone currently open and planned. This milestone will bring some API changes and improvements and will ensure compatibility with the upcoming ReactPHP `v3`.  Also talked with @clue that redis `v3` probably won't be compatible with ReactPHP `v1`, so we'll have to wait for the ReactPHP `v3` components before releasing redis `v3`.

With all this in mind, I think it's safe to say that redis `v3` will take a while before going live, but we think it's a good idea to backport some features (PHP 8.3 compatibility from #147, promise `v3` support from #150, etc.) to `v2`. We can then release an additional version for `v2`, so you can use this version for now until redis `v3` gets released.

We'll work on backporting the needed features, will keep you posted as we progress :+1:

**Comment by WyriHaximus** [comment]
Sounds like a plan @SimonFrings, it was mainly about unlocking the way done in https://github.com/clue/reactphp-redis/pull/152 . Template types and such will come in v3, doing a simular pattern with my own packages where one release will unlock it, and the next will drop previous version + adds all the v3 goodies.

**Comment by yadaiio** [comment]
Closed via #152.

**Comment by WyriHaximus** [comment]
Thanks, just released https://github.com/WyriHaximus/reactphp-cache-redis/releases/tag/4.5.0 with that release :+1:
