### ISSUE TITLE
High availability (Redis Sentinel)

### ISSUE THREAD

**Issue by sm2017** [clue/reactphp-redis#69]
See https://redis.io/topics/sentinel
As this redis client don't support Sentinel , How we can have high availability redis?
Can you implement Sentinel protocol?

**Comment by sm2017** [comment]
See also https://github.com/lancerhe/php-redis-sentinel

**Comment by clue** [comment]
I think that this feature makes perfect sense and would love to see support for this in this library :+1:

Implementing support for this here sounds reasonable and does not require implementing the "sentinel protocol", you merely have to accept a number of redis instances and send a command to them to get the master address. See also https://redis.io/topics/sentinel-clients for more details.

As much as I'd love to see this feature in, there are currently no immediate plans to build this from my end (no demand at the moment). But I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and you want a quote, please check out my profile and send me an email)*

**Comment by clue** [comment]
I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and if you want to sponsor this feature, feel free to reach out and send me an email)*
