### ISSUE TITLE
Support Redis Cluster Specification (e.g. AWS Elasticache Redis Cluster)

### ISSUE THREAD

**Issue by vanht** [clue/reactphp-redis#78]
Hi all,
I connect success to Elasticache redis, pub/sub no problem, but sadd/smembers no success.
I think same problem [MOVED Redirect fails](https://github.com/Salakar/sails-ioredis/issues/4) , you can help me?
Thank all.

**Comment by clue** [comment]
@vanht Thanks for bringing this up!

This project does not currently implement the [Redis Cluster Specification](https://redis.io/topics/cluster-spec#moved-redirection). In cluster mode, a single node may ask you to redirect your command to another node like this:

```php
GET x
-MOVED 3999 127.0.0.1:6381
```

You can still catch this exception and manually create a new connection to the given node address and then re-issue your command.

In this future, we may want to handle this automatically within this library. Implementation wise this sounds reasonable and shouldn't require too much effort.

However, as much as I'd love to see this feature in, there are currently no immediate plans to build this from my end (no demand at the moment). But I would be really happy to accept PRs +1

*(If you need this for a commercial project and you want a quote, please check out my profile and send me an email)*

**Comment by clue** [comment]
I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and if you want to sponsor this feature, feel free to reach out and send me an email)*
