### ISSUE TITLE
Lazy connection

### ISSUE THREAD

**Issue by WyriHaximus** [clue/reactphp-redis#80]
Are there plans to have a lazy connection support just like https://github.com/friends-of-reactphp/mysql/pull/87 ?

**Comment by clue** [comment]
@WyriHaximus Absolutely! I think this design would be a perfect fit for this project!

That being said, there are no immediate plans to build this from my end (more important outstanding issues at the moment). If anybody feels like sponsoring this development, please reach out! :shipit: :+1:

**Comment by matt-stam** [comment]
I would absolutely love to see the lazy connection support added as well. Thanks for all the good stuff @clue!

**Comment by WyriHaximus** [comment]
Just started working on this, with some luck I'll have a PR up later tonight

**Comment by WyriHaximus** [comment]
Work In Progress PR is up at: https://github.com/clue/reactphp-redis/pull/82
