### ISSUE TITLE
Improve documentation for MULTI / EXEC

### ISSUE THREAD

**Issue by francislavoie** [clue/reactphp-redis#91]
I mostly just want to clarify how to use MULTI / EXEC in an async/promise context.

How should code be structured when doing MULTI?

```php
$client->multi()->then(function() use ($client) {
    $client->get('a', 'b');
    $client->get('c', 'd');
    return $client->exec()->then(function($data) {
        return doSomething($data);
    });
});
```

or...

```php
$client->multi();
$client->get('a', 'b');
$client->get('c', 'd');
return $client->exec()->then(function($data) {
	return doSomething($data);
});
```

etc.

**Comment by clue** [comment]
@francislavoie Excellent question! The answer would depend on what you're trying to achieve, so I think https://redis.io/topics/transactions will give you a good overview about possible options.

In general, the `MULTI` command *starts* an transaction for all following commands and you really only care about the results when executing the `EXEC` command. In other words: Most of the times, you would use your second suggestion and use the `$data` array to access all results from the previously queued operations.

I hope this helps :+1:
