### ISSUE TITLE
LazyClient: no error messages

### ISSUE THREAD

**Issue by Logioniz** [clue/reactphp-redis#92]
Suppose I have a redis process running on a standard port and in my code I make a mistake by incorrectly specifying the port. How do I know about the error?

```php
<?php

$loader = require __DIR__ . '/vendor/autoload.php';

use \Clue\React\Redis\Factory;
use \Clue\React\Redis\Client;

$loop = React\EventLoop\Factory::create();

$factory = new Factory($loop);

$client = $factory->createLazyClient('redis://127.0.0.1:9006');

$client->on('error', function (Exception $e) {
    echo "Error: " . $e . PHP_EOL;
});

$client->on('close', function () {
    echo "Connection closed" . PHP_EOL;
});

$client->set('qwe', 1234)->then(function ($r) use ($loop) {
    $loop->stop();
});

$loop->run();

```

**Comment by clue** [comment]
@Logioniz Thanks for raising this question!

If the connection fails (for whatever reason), it will reject all outstanding commands like this:

```php
$client->set('qwe', 1234)->then(function ($r) use ($loop) {
    var_dump('done', $r);
}, function (Exception $e) {
    echo 'Error: ' . $e->getMessage() . PHP_EOL;
});
```

This is covered by the documentation:


> If the underlying database connection fails, it will reject all outstanding commands and will return to the initial "idle" state. This means that you can keep sending additional commands at a later time which will again try to open a new underlying connection.

https://github.com/clue/reactphp-redis#createlazyclient

**Comment by Logioniz** [comment]
> This is covered by the documentation

Okey, thanks.

A mistake that I receive misinforms me.

> $ php 1.php
> Error: Connection closing
> $ 

_Connection closing_ means that connection was open and now it closing.

I expect to see an error _Connection refused_ when connection was never open and _Connection closed_ when connection was open and now it closed.

**Comment by clue** [comment]
I agree that it should report a "connection refused" error in this case. Can you verify the connection is actually refused and that nothing is listening on this port? (#79)

**Comment by Logioniz** [comment]
> Can you verify the connection is actually refused and that nothing is listening on this port? 

You are right, docker-proxy misinform me. He listens to the port in the host OS at a time when nobody listens to the port in the container.

Now I get this error after a long timeout:

> Error: Connection to Redis server failed because underlying transport connection failed

what is the reason for the long timeout?

**Comment by clue** [comment]
Can you provide a gist to reproduce the problem you're seeing?

You can always take a look at `$exception->getPrevious()` to get access to any nested exceptions (if any).

Your problem seems to suggest the TCP/IP connection is timing out. This is again covered by the documentation:

> This method respects PHP's default_socket_timeout setting (default 60s) as a timeout for establishing the underlying connection and waiting for successful authentication. You can explicitly pass a custom timeout value in seconds (or use a negative number to not apply a timeout) like this:
>
> $factory->createLazyClient('localhost?timeout=0.5');

**Comment by Logioniz** [comment]
Its very strange because another tools get answer very quickly:
```
$ ss -ntlp | grep 12345
$ cat 3.php 
<?php

$loader = require __DIR__ . '/vendor/autoload.php';

use \Clue\React\Redis\Factory;
use \Clue\React\Redis\Client;

$loop = React\EventLoop\Factory::create();

$factory = new Factory($loop);

$client = $factory->createLazyClient('redis://127.0.0.1:12345');

$client->on('error', function (Exception $e) {
    echo "Error: " . $e . PHP_EOL;
});

$client->on('close', function () {
    echo "Connection closed" . PHP_EOL;
});

$client->set('qwe', 1234)->then(
    function ($r) use ($loop) {
        $loop->stop();
    },
    function (Exception $e) use ($loop) {
        echo 'Error: ' . $e->getMessage() . PHP_EOL;
        echo 'Previous ' . $e->getPrevious()->getMessage() . PHP_EOL;
        $loop->stop();
    }
);

$loop->run();
$ time php 3.php 
Error: Connection to Redis server failed because underlying transport connection failed
Previous Connection to 127.0.0.1:12345 timed out after 60 seconds

real    1m0,097s
user    0m0,026s
sys 0m0,017s
$ cat 4.php
<?php

ini_set('default_socket_timeout', 60);

$socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
$result = socket_connect($socket, '127.0.0.1', 12345);

if ($result === false) {
    echo "Error: " . socket_strerror(socket_last_error($socket)) . "\n";
} else {
    echo "Success" . PHP_EOL;
}
$ time php 4.php 
PHP Warning:  socket_connect(): unable to connect [111]: Connection refused in /home/logioniz/Work/sape/reactphp/4.php on line 6
Error: Connection refused

real    0m0,037s
user    0m0,013s
sys 0m0,012s
$ time nc 127.0.0.1 12345

real    0m0,002s
user    0m0,002s
sys 0m0,000s
$ time nc -v 127.0.0.1 12345
nc: connect to 127.0.0.1 port 12345 (tcp) failed: Connection refused

real    0m0,003s
user    0m0,002s
sys 0m0,000s
$ 
```

**Comment by Logioniz** [comment]
It seems that problem in event loop.
Here short output of strace 3.php:
```
...
epoll_create1(EPOLL_CLOEXEC)            = 3
...
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 9
...
connect(9, {sa_family=AF_INET, sin_port=htons(12345), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
...
epoll_ctl(3, EPOLL_CTL_ADD, 9, {EPOLLIN, {u32=4294967295, u64=18446744073709551615}}) = 0
epoll_ctl(3, EPOLL_CTL_DEL, 9, 0x7ffd406f580c) = 0
ioctl(9, FIONBIO, [1])                  = 0
epoll_ctl(3, EPOLL_CTL_DEL, 9, 0x7ffd406f586c) = -1 ENOENT (No such file or directory)
....
epoll_ctl(3, EPOLL_CTL_ADD, 6, {EPOLLIN, {u32=6, u64=6}}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 8, {EPOLLIN, {u32=8, u64=8}}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 9, {EPOLLOUT, {u32=9, u64=9}}) = 0
epoll_wait(3, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=9, u64=9}}], 1024, 59986) = 1
epoll_wait(3, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=9, u64=9}}], 1024, 59986) = 1
epoll_ctl(3, EPOLL_CTL_DEL, 9, 0x7ffd406f2870) = 0
epoll_wait(3, ^Cstrace: Process 31120 detached
 <detached ...>
```

The 9th descriptor was closed and removed from the event loop.

I do not know why we need the [Factory](https://github.com/reactphp/event-loop/blob/master/src/Factory.php) class, which does not allow to choose a event-loop :-).

Do you know how to set event-loop in reactphp manually?

I have preinstalled uv-beta.

**Comment by Logioniz** [comment]
@clue, thanks.
I change event loop to libev and the problem is gone.

**Comment by clue** [comment]
@Logioniz Thanks for diving into this and reporting back a possible work around!

This really shouldn't have happened, no matter which event loop implementation you're using, so it looks like a bug in either the EventLoop or the Socket component. Can you file an issue upstream and link to this ticket and I'll make sure to also poke @WyriHaximus so we can take a look at this? :shipit:

**Comment by Logioniz** [comment]
I created topic in react-php/event-loop with this problem https://github.com/reactphp/event-loop/issues/188.
Also remove redis client, because he is not guilty.

**Comment by WyriHaximus** [comment]
Will have a look at this @clue, thanks for the report @Logioniz  :+1:
