### ISSUE TITLE
Documentation on Queues (list blpop)

### ISSUE THREAD

**Issue by rijnhard** [clue/reactphp-redis#95]
Hi

Are there any (or can we get) examples on using this with `blpop`?

**Comment by clue** [comment]
@rijnhard Thanks for this question!

This project maps all commands to method calls as is. For the [`BLPOP`](https://redis.io/commands/BLPOP) command, this means you can simply invoke it like this:

```php
$client->blpop('list', '60')->then(function ($value) {
    if ($value === null) {
        echo 'Nothing in the list' . PHP_EOL;
    } else {
        echo 'Here\'s the value: ' . $value . PHP_EOL;
    }
});
```

I hope this helps! :+1:

**Comment by rijnhard** [comment]
Just as a note: the reason why I asked is because of the blocking semantics and that there's usually additional considerations or special case behaviour associated with it in other libraries

**Comment by clue** [comment]
@rijnhard Fair point and very valid question. I think one of the things that sets this library apart from others is the fact that it doesn't implement any special behavior for any of its commands.

Regarding blocking commands ("blocking" on the server side), this means that any following commands may be "delayed" in the pipeline of outstanding commands:

```php
$client->blpop('list', '60')->then($doTheThing);
$client->get('key')->then($processValue);
```

In this example, the following `GET` command may be delayed by up to 60 seconds. Depending on the use case, you may use a smaller timeout value or a second connection to avoid blocking.

**Comment by rijnhard** [comment]
@clue most Redis libraries require a separate connection for a blocking command like BLPOP, but in my experience, most people don't know this until they trip on it.

It may be worth having a `blpop` example, but if any users know how to search then hopefully they will find this, but thank you for the clarity, this will help others.

**Comment by clue** [comment]
@rijnhard I think this support ticket is always a good first step because it allows others to also discover these solutions. I'm not sure how to best address all these implementations details in the documentation, but if you have an idea on how we can improve the documentation, PRs are very much welcome! :shipit:
